const directoryUrl = 'https://igod.gov.in/';

const entries = [
  ['Union Ministry', 'AYUSH (MoA)'],
  ['Union Ministry', 'Agriculture and Farmers Welfare (MoAFW)'],
  ['Union Ministry', 'Chemicals and Fertilizers (MoCF)'],
  ['Union Ministry', 'Civil Aviation (MoCA)'],
  ['Union Ministry', 'Coal'],
  ['Union Ministry', 'Commerce and Industry (MoCI)'],
  ['Union Ministry', 'Communications (MoC)'],
  ['Union Ministry', 'Consumer Affairs, Food and Public Distribution (MoCAFP)'],
  ['Union Ministry', 'Cooperation'],
  ['Union Ministry', 'Corporate Affairs (MCA)'],
  ['Union Ministry', 'Culture'],
  ['Union Ministry', 'Defence (MoD)'],
  ['Union Ministry', 'Development of North Eastern Region (MDONER)'],
  ['Union Ministry', 'Earth Sciences (MoES)'],
  ['Union Ministry', 'Education (MoE)'],
  ['Union Ministry', 'Electronics and Information Technology (MeitY)'],
  ['Union Ministry', 'Environment, Forest and Climate Change (MoEFCC)'],
  ['Union Ministry', 'External Affairs (MEA)'],
  ['Union Ministry', 'Finance (MoF)'],
  ['Union Ministry', 'Fisheries, Animal Husbandry and Dairying (MoFAHD)'],
  ['Union Ministry', 'Food Processing Industries (MoFPI)'],
  ['Union Ministry', 'Health and Family Welfare (MoHFW)'],
  ['Union Ministry', 'Heavy Industries (MoHI)'],
  ['Union Ministry', 'Home Affairs (MHA)'],
  ['Union Ministry', 'Housing and Urban Affairs (MoHUA)'],
  ['Union Ministry', 'Information and Broadcasting (MIB)'],
  ['Union Ministry', 'Jal Shakti (MoJS)'],
  ['Union Ministry', 'Labour and Employment (MoLE)'],
  ['Union Ministry', 'Law and Justice (MoLJ)'],
  ['Union Ministry', 'Micro, Small & Medium Enterprises (MSME)'],
  ['Union Ministry', 'Mines (MoM)'],
  ['Union Ministry', 'Minority Affairs (MoMA)'],
  ['Union Ministry', 'New and Renewable Energy (MNRE)'],
  ['Union Ministry', 'Panchayati Raj (MoPR)'],
  ['Union Ministry', 'Parliamentary Affairs (MPA)'],
  ['Union Ministry', 'Personnel, Public Grievances and Pensions (MoPPGP)'],
  ['Union Ministry', 'Petroleum and Natural Gas (MoPNG)'],
  ['Union Ministry', 'Planning (MoP)'],
  ['Union Ministry', 'Ports, Shipping and Waterways (MoPSW)'],
  ['Union Ministry', 'Power'],
  ['Union Ministry', 'Railways (MoR)'],
  ['Union Ministry', 'Road Transport and Highways (MoRTH)'],
  ['Union Ministry', 'Rural Development (MoRD)'],
  ['Union Ministry', 'Science and Technology (MST)'],
  ['Union Ministry', 'Skill Development and Entrepreneurship (MSDE)'],
  ['Union Ministry', 'Social Justice and Empowerment (MoSJE)'],
  ['Union Ministry', 'Statistics and Programme Implementation (MoSPI)'],
  ['Union Ministry', 'Steel (MoS)'],
  ['Union Ministry', 'Textiles (MoT)'],
  ['Union Ministry', 'Tourism'],
  ['Union Ministry', 'Tribal Affairs (MoTA)'],
  ['Union Ministry', 'Women and Child Development (MoWCD)'],
  ['Union Ministry', 'Youth Affairs and Sports (MoYAS)'],
  ['Union Department', 'Department for Promotion of Industry and Internal Trade (DPIIT)'],
  ['Union Department', 'Department of Administrative Reforms and Public Grievances (DARPG)'],
  ['Union Department', 'Department of Agricultural Research and Education (DARE)'],
  ['Union Department', 'Department of Agriculture and Farmers Welfare (DoAFW)'],
  ['Union Department', 'Department of Animal Husbandry and Dairying (DoAHD)'],
  ['Union Department', 'Department of Biotechnology (DBT)'],
  ['Union Department', 'Department of Border Management (DoBM)'],
  ['Union Department', 'Department of Capital Development (DCD)'],
  ['Union Department', 'Department of Chemicals and Petro-Chemicals (DoCP)'],
  ['Union Department', 'Department of Commerce (DoC)'],
  ['Union Department', 'Department of Consumer Affairs (DoCA)'],
  ['Union Department', 'Department of Defence (DoD)'],
  ['Union Department', 'Department of Defence Production (DDP)'],
  ['Union Department', 'Department of Defence Research and Development (DRDO)'],
  ['Union Department', 'Department of Drinking Water and Sanitation (DDWS)'],
  ['Union Department', 'Department of Economic Affairs (DEA)'],
  ['Union Department', 'Department of Empowerment of Persons with Disabilities (DEPWD)'],
  ['Union Department', 'Department of Ex-Servicemen Welfare (DESW)'],
  ['Union Department', 'Department of Expenditure (DoE)'],
  ['Union Department', 'Department of Fertilizers (DoFz)'],
  ['Union Department', 'Department of Financial Services (DoFS)'],
  ['Union Department', 'Department of Fisheries (DoF)'],
  ['Union Department', 'Department of Food and Public Distribution (DFPD)'],
  ['Union Department', 'Department of Health Research (DHR)'],
  ['Union Department', 'Department of Health and Family Welfare (DoHFW)'],
  ['Union Department', 'Department of Higher Education (DoHE)'],
  ['Union Department', 'Department of Home (DoH)'],
  ['Union Department', 'Department of Investment and Public Asset Management (DIPAM)'],
  ['Union Department', 'Department of Justice (DoJ)'],
  ['Union Department', 'Department of Land Resources (DLR)'],
  ['Union Department', 'Department of Legal Affairs (DoLA)'],
  ['Union Department', 'Department of Military Affairs (DMA)'],
  ['Union Department', 'Department of Official Language (DoOL)'],
  ['Union Department', "Department of Pension & Pensioner's Welfare (DoPPW)"],
  ['Union Department', 'Department of Personnel and Training (DoPT)'],
  ['Union Department', 'Department of Pharmaceuticals (DoPs)'],
  ['Union Department', 'Department of Posts (DoP)'],
  ['Union Department', 'Department of Public Enterprises (DPE)'],
  ['Union Department', 'Department of Revenue (DoR)'],
  ['Union Department', 'Department of Rural Development (DoRD)'],
  ['Union Department', 'Department of School Education and Literacy (DSEL)'],
  ['Union Department', 'Department of Science and Technology (DST)'],
  ['Union Department', 'Department of Scientific and Industrial Research (DSIR)'],
  ['Union Department', 'Department of Social Justice and Empowerment (DoSJE)'],
  ['Union Department', 'Department of Sports (DoS)'],
  ['Union Department', 'Department of Telecommunications (DoT)'],
  ['Union Department', 'Department of Urban Development (DUD)'],
  ['Union Department', 'Department of Water Resources, River Development and Ganga Rejuvenation (DoWRGR)'],
  ['Union Department', 'Department of Youth Affairs (DoYA)'],
  ['Union Department', 'Legislative Department (LD)'],
  ['Maharashtra', 'Agriculture Department, Maharashtra'],
  ['Maharashtra', 'Animal Husbandry Department, Maharashtra'],
  ['Maharashtra', 'Co-operation, Marketing and Textiles Department, Maharashtra'],
  ['Maharashtra', 'Cultural Affairs Department, Maharashtra'],
  ['Maharashtra', 'Dairy Development Department, Maharashtra'],
  ['Maharashtra', 'Environment and Climate Change Department, Maharashtra'],
  ['Maharashtra', 'Finance Department, Maharashtra'],
  ['Maharashtra', 'Fisheries Department, Maharashtra'],
  ['Maharashtra', 'Food, Civil Supplies and Consumer Protection Department, Maharashtra'],
  ['Maharashtra', 'Forest Department, Maharashtra'],
  ['Maharashtra', 'General Administration Department, Maharashtra'],
  ['Maharashtra', 'Goods and Services Tax Department, Maharashtra'],
  ['Maharashtra', 'Greater Mumbai Police, Maharashtra'],
  ['Maharashtra', 'Higher and Technical Education Department, Maharashtra'],
  ['Maharashtra', 'Home Department, Maharashtra'],
  ['Maharashtra', 'Housing Department, Maharashtra'],
  ['Maharashtra', 'Labour Department, Maharashtra'],
  ['Maharashtra', 'Law and Judiciary Department, Maharashtra'],
  ['Maharashtra', 'Maharashtra Cyber Department'],
  ['Maharashtra', 'Marathi Language Department'],
  ['Maharashtra', 'Medical Education and Drugs Department, Maharashtra'],
  ['Maharashtra', 'Minority Development Department, Maharashtra'],
  ['Maharashtra', 'Motor Vehicles Department ( R.T.O.), Maharashtra'],
  ['Maharashtra', 'Other Backward Bahujan Welfare Department, Maharashtra'],
  ['Maharashtra', 'Parliamentary Affairs Department, Maharashtra'],
  ['Maharashtra', 'Planning Department, Maharashtra'],
  ['Maharashtra', 'Public Health and Family Welfare Department, Maharashtra'],
  ['Maharashtra', 'Public Works Department, Maharashtra'],
  ['Maharashtra', 'Registration and Stamps Department, Maharashtra'],
  ['Maharashtra', 'Revenue and Forest Department, Maharashtra'],
  ['Maharashtra', 'Rural Development and Panchayat Raj Department, Maharashtra'],
  ['Maharashtra', 'Sainik Welfare Department, Maharashtra'],
  ['Maharashtra', 'School Education and Sports Department, Maharashtra'],
  ['Maharashtra', 'Skills, Employment, Entrepreneurship and Innovation Department, Maharashtra'],
  ['Maharashtra', 'Social Justice and Special Assistance Department, Maharashtra'],
  ['Maharashtra', 'Textiles Department, Maharashtra'],
  ['Maharashtra', 'Tourism Department, Maharashtra'],
  ['Maharashtra', 'Tribal Development Department, Maharashtra'],
  ['Maharashtra', 'Water Conservation Department, Maharashtra'],
  ['Maharashtra', 'Water Resources Department, Maharashtra'],
  ['Maharashtra', 'Water Supply and Sanitation Department, Maharashtra'],
  ['Maharashtra', 'Women and Child Development Department, Maharashtra']
];

const codePrefixes = { 'Union Ministry': 'UM', 'Union Department': 'UD', Maharashtra: 'MH' };
const sourcePaths = {
  'Union Ministry': 'ug/E002/organizations',
  'Union Department': 'ug/E003/organizations',
  Maharashtra: 'sg/MH/E003/organizations'
};
const counters = new Map();

module.exports = entries.map(([governmentLevel, name]) => {
  const number = (counters.get(governmentLevel) || 0) + 1;
  counters.set(governmentLevel, number);

  return {
    governmentLevel,
    name,
    code: `${codePrefixes[governmentLevel]}${String(number).padStart(3, '0')}`,
    description: 'Official government ministry or department.',
    sourceUrl: `${directoryUrl}${sourcePaths[governmentLevel]}`,
    isOfficial: true
  };
});